version: '3'

services:

  nodejs:
    image: pinaka30/stone-paper-scissor:latest
    container_name: stone-paper-scissor
    ports:
      - ${PORT_SERVER}:8000
    depends_on:
      - redis-cache
    environment:
      - REDIS_HOST=redis-cache
      - REDIS_PORT=${PORT_REDIS}

  redis-cache:
    image: redis
    container_name: redis-cache
    ports:
      - ${PORT_REDIS}:6379
